name: K6 Extension Workflow
on: 
  workflow_dispatch:

jobs:
  k6_local_test:
    name: k6 counter extension run
    runs-on: ubuntu-latest
    container: docker://golang:1.17-alpine
    env:
          SLACK_TOKEN : ${{ secrets.SLACK_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: testing.js
