name: K6 Extension Workflow
on: 
  workflow_dispatch:
  # For manual input when trigger the workflow
    inputs:
      target: 
        description: 'Target'
        required: true
        default: '1'
      
      duration: 
        description: 'Duration (in second)'
        required: true
        default: '10'

jobs:
  k6_local_test:
    name: k6 counter extension run
    runs-on: ubuntu-latest
    container: docker://golang:1.17-alpine
    env:
          SLACK_TOKEN : ${{ secrets.SLACK_TOKEN }}
          TARGET : ${{ github.event.inputs.target }}
          DURATION : ${{ github.event.inputs.duration }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: testing.js
